// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.4
// source: proto/mfa.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MfaService_GetQRcodeImg_FullMethodName = "/mfa.MfaService/GetQRcodeImg"
)

// MfaServiceClient is the client API for MfaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MfaServiceClient interface {
	GetQRcodeImg(ctx context.Context, in *QRcodeRequest, opts ...grpc.CallOption) (*QRcodeResponse, error)
}

type mfaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMfaServiceClient(cc grpc.ClientConnInterface) MfaServiceClient {
	return &mfaServiceClient{cc}
}

func (c *mfaServiceClient) GetQRcodeImg(ctx context.Context, in *QRcodeRequest, opts ...grpc.CallOption) (*QRcodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QRcodeResponse)
	err := c.cc.Invoke(ctx, MfaService_GetQRcodeImg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MfaServiceServer is the server API for MfaService service.
// All implementations must embed UnimplementedMfaServiceServer
// for forward compatibility.
type MfaServiceServer interface {
	GetQRcodeImg(context.Context, *QRcodeRequest) (*QRcodeResponse, error)
	mustEmbedUnimplementedMfaServiceServer()
}

// UnimplementedMfaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMfaServiceServer struct{}

func (UnimplementedMfaServiceServer) GetQRcodeImg(context.Context, *QRcodeRequest) (*QRcodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQRcodeImg not implemented")
}
func (UnimplementedMfaServiceServer) mustEmbedUnimplementedMfaServiceServer() {}
func (UnimplementedMfaServiceServer) testEmbeddedByValue()                    {}

// UnsafeMfaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MfaServiceServer will
// result in compilation errors.
type UnsafeMfaServiceServer interface {
	mustEmbedUnimplementedMfaServiceServer()
}

func RegisterMfaServiceServer(s grpc.ServiceRegistrar, srv MfaServiceServer) {
	// If the following call pancis, it indicates UnimplementedMfaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MfaService_ServiceDesc, srv)
}

func _MfaService_GetQRcodeImg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QRcodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MfaServiceServer).GetQRcodeImg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MfaService_GetQRcodeImg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MfaServiceServer).GetQRcodeImg(ctx, req.(*QRcodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MfaService_ServiceDesc is the grpc.ServiceDesc for MfaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MfaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mfa.MfaService",
	HandlerType: (*MfaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQRcodeImg",
			Handler:    _MfaService_GetQRcodeImg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mfa.proto",
}
